---
title: DATA 550 Final Project - Analysis of Heart Failure Clinical Records
author: Sarina Attri
output: github_document
---

------------------------------------------------------------------------

## Repository Contents

The repository contains two main subdirectories. The `code` directory contains the R code files that generate each output. The `output` directory contains the `.rds` files that are generated from the code files. 

Files stored directly in the repository include:
- The file that creates the report, `final_project.Rmd`
- The raw data, `heart_failure_clinical_records_dataset.csv`
- The `Makefile`, which contains the rules to create individual outputs as well as the overall report
- The `README.Rmd` file, which produces `README.md` file that is displayed in GitHub
- A `.gitignore` file, to prevent outputs and irrelevant files from being tracked by Git

(insert info about Rmd, csv, README, Makefile, html)

## How to Generate Final Report

The `Makefile` contains rules for building the report. `code/render_code.R` contains the code to render the report, which is called `final_project.Rmd`. The final report is called `final_project.html` and can be generated by executing `make` in the Terminal.

## Contents of Final Report

The final report contains descriptive statistics, logistic regression results, and a figure to characterize the relationship between different clinical factors and odds of death.

## Code for Loading Data

- The `code/data_code.R` file loads the CSV file from the repository and stores it in the output folder as `data.rds`

## Code for Generating Tables

- The `code/descriptive_code.R` file creates *Table 1*, which shows the descriptive characteristics of patients by survival
- The `code/regression_code.R` file creates *Table 2*, which displays the results of the logistic regression model

## Code for Generating Figure

- The `code/figure_code.R` file creates *Figure 1*, which visualizes the the probability of death by serum creatinine levels and sex

